INSERT INTO html_colours(RGB_code, name, notes) VALUES

('800000', 'maroon', NULL),
('8B0000', 'darkred', NULL),
('FF0000', 'red', NULL),
('FFB6C1', 'lightpink', NULL),
('DC143C', 'crimson', NULL),

('DB7093', 'palevioletred', NULL),
('FF69B4', 'hotpink', NULL),
('FF1493', 'deeppink', NULL),
('C71585', 'mediumvioletred', NULL),
('800080', 'purple', NULL),

('8B008B', 'darkmagenta', NULL),
('DA70D6', 'orchid', NULL),
('D8BFD8', 'thistle', NULL),
('DDA0DD', 'plum', NULL),
('EE82EE', 'violet', NULL),

('FF00FF', 'fuchsia', NULL),
('FF00FF', 'magenta', NULL),
('BA55D3', 'mediumorchid', NULL),
('9400D3', 'darkviolet', NULL),
('9932CC', 'darkorchid', NULL),

('8A2BE2', 'blueviolet', NULL),
('4B0082', 'indigo', NULL),
('9370DB', 'mediumpurple', NULL),
('6A5ACD', 'slateblue', NULL),
('7B68EE', 'mediumslateblue', NULL),

('00008B', 'darkblue', NULL),
('0000CD', 'mediumblue', NULL),
('0000FF', 'blue', NULL),
('000080', 'navy', NULL),
('191970', 'midnightblue', NULL),

('483D8B', 'darkslateblue', NULL),
('4169E1', 'royalblue', NULL),
('6495ED', 'cornflowerblue', NULL),
('B0C4DE', 'lightsteelblue', NULL),
('F0F8FF', 'aliceblue', NULL),

('F8F8FF', 'ghostwhite', NULL),
('E6E6FA', 'lavender', NULL),
('1E90FF', 'dodgerblue', NULL),
('4682B4', 'steelblue', NULL),
('00BFFF', 'deepskyblue', NULL),

('708090', 'slategray', NULL),
('778899', 'lightslategray', NULL),
('87CEFA', 'lightskyblue', NULL),
('87CEEB', 'skyblue', NULL),
('ADD8E6', 'lightblue', NULL),

('008080', 'teal', NULL),
('008B8B', 'darkcyan', NULL),
('00CED1', 'darkturquoise', NULL),
('00FFFF', 'aqua, cyan', NULL),
('48D1CC', 'mediumturquoise', NULL),

('5F9EA0', 'cadetblue', NULL),
('AFEEEE', 'paleturquoise', NULL),
('E0FFFF', 'lightcyan', NULL),
('F0FFFF', 'azure', NULL),
('20B2AA', 'lightseagreen', NULL),

('40E0D0', 'turquoise', NULL),
('B0E0E6', 'powderblue', NULL),
('2F4F4F', 'darkslategray', NULL),
('7FFFD4', 'aquamarine', NULL),
('00FA9A', 'mediumspringgreen', NULL),

('66CDAA', 'mediumaquamarine', NULL),
('00FF7F', 'springgreen', NULL),
('3CB371', 'mediumseagreen', NULL),
('2E8B57', 'seagreen', NULL),
('32CD32', 'limegreen', NULL),

('006400', 'darkgreen', NULL),
('008000', 'green', NULL),
('00FF00', 'lime', NULL),
('228B22', 'forestgreen', NULL),
('8FBC8F', 'darkseagreen', NULL),

('90EE90', 'lightgreen', NULL),
('98FB98', 'palegreen', NULL),
('F5FFFA', 'mintcream', NULL),
('F0FFF0', 'honeydew', NULL),
('7FFF00', 'chartreuse', NULL),

('7CFC00', 'lawngreen', NULL),
('6B8E23', 'olivedrab', NULL),
('556B2F', 'darkolivegreen', NULL),
('9ACD32', 'yellowgreen', NULL),
('ADFF2F', 'greenyellow', NULL),

('F5F5DC', 'beige', NULL),
('FAF0E6', 'linen', NULL),
('FAFAD2', 'lightgoldenrodyellow', NULL),
('808000', 'olive', NULL),
('FFFF00', 'yellow', NULL),

('FFFFE0', 'lightyellow', NULL),
('FFFFF0', 'ivory', NULL),
('BDB76B', 'darkkhaki', NULL),
('F0E68C', 'khaki', NULL),
('EEE8AA', 'palegoldenrod', NULL),

('F5DEB3', 'wheat', NULL),
('FFD700', 'gold', NULL),
('FFFACD', 'lemonchiffon', NULL),
('FFEFD5', 'papayawhip', NULL),
('B8860B', 'darkgoldenrod', NULL),

('DAA520', 'goldenrod', NULL),
('FAEBD7', 'antiquewhite', NULL),
('FFF8DC', 'cornsilk', NULL),
('FDF5E6', 'oldlace', NULL),
('FFE4B5', 'moccasin', NULL),

('FFDEAD', 'navajowhite', NULL),
('FFA500', 'orange', NULL),
('FFE4C4', 'bisque', NULL),
('D2B48C', 'tan', NULL),
('FF8C00', 'darkorange', NULL),

('DEB887', 'burlywood', NULL),
('8B4513', 'saddlebrown', NULL),
('F4A460', 'sandybrown', NULL),
('FFEBCD', 'blanchedalmond', NULL),
('FFF0F5', 'lavenderblush', NULL),

('FFF5EE', 'seashell', NULL),
('FFFAF0', 'floralwhite', NULL),
('FFFAFA', 'snow', NULL),
('CD853F', 'peru', NULL),
('FFDAB9', 'peachpuff', NULL),

('D2691E', 'chocolate', NULL),
('A0522D', 'sienna', NULL),
('FFA07A', 'lightsalmon', NULL),
('FF7F50', 'coral', NULL),
('E9967A', 'darksalmon', NULL),

('FFE4E1', 'mistyrose', NULL),
('FF4500', 'orangered', NULL),
('FA8072', 'salmon', NULL),
('FF6347', 'tomato', NULL),
('BC8F8F', 'rosybrown', NULL),

('FFC0CB', 'pink', NULL),
('CD5C5C', 'indianred', NULL),
('F08080', 'lightcoral', NULL),
('A52A2A', 'brown', NULL),
('B22222', 'firebrick', NULL),

('000000', 'black', NULL),
('696969', 'dimgray', NULL),
('808080', 'gray', NULL),
('A9A9A9', 'darkgray', NULL),
('C0C0C0', 'silver', NULL),

('D3D3D3', 'lightgrey', NULL),
('DCDCDC', 'gainsboro', NULL),
('F5F5F5', 'whitesmoke', NULL),
('FFFFFF', 'white');

