-- SET NAMES utf8mb4;
-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';
-- SET @old_autocommit=@@autocommit;
-- SET AUTOCOMMIT=0;

USE farming; -- Well, the tables CREATE-d and INSERT-ed-INTO in this file
             -- might live in their own CREATE-d DATABASE

-- DROP TABLE plant_families; DROP TABLE in_family;
DROP TABLE IF EXISTS plant_families, in_family, in_order;

CREATE TABLE plant_families ( -- plant families
  -- family_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  family VARCHAR(50) NOT NULL,
  traits VARCHAR(1999), -- change to 'order', upper grouping that it belongs in
  description TEXT(1999),
  inflorescence_and_flowers VARCHAR(1999),
  fruits_and_seeds          VARCHAR(1999),
  phytochemistry            VARCHAR(1999),
  photosynthesis            VARCHAR(1999),
  distribution              VARCHAR(1999),
  economics                    TEXT(1999),
  PRIMARY KEY  (family)
  -- PRIMARY KEY  (family_id)
  -- KEY idx_family (family)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE in_family ( -- plant families
  -- family_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  plant_name VARCHAR(99) NOT NULL,
  family     VARCHAR(50) NOT NULL,
  language_code VARCHAR(2) NOT NULL DEFAULT 'en',
  PRIMARY KEY (plant_name),
  KEY idx_family (family),
  FOREIGN KEY (family)  REFERENCES plant_families(family),
  FOREIGN KEY (language_code) REFERENCES general.languages(code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE in_order ( -- plant orders
  -- order_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  family          VARCHAR(50) NOT NULL,
  plant_order     VARCHAR(50) NOT NULL, -- ORDER is a reserved word
  language_code VARCHAR(2) NOT NULL DEFAULT 'en',
  PRIMARY KEY (family),
  KEY idx_order (plant_order),
-- FOREIGN KEY (family)  REFERENCES plant_families(family),
  FOREIGN KEY (language_code) REFERENCES general.languages(code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO in_order (family, plant_order, language_code) VALUES
-- ('FAMILY', 'ORDER', 'LANG-CODE'),
-- ('FAMILY', 'ORDER', 'LANG-CODE'),
-- ('FAMILY', 'ORDER', 'LANG-CODE'),
('Platanaceae', 'Proteales', 'en'), -- plane trees
('Nelumbonaceae', 'Proteales', 'en'), -- the sacred lotus
('Sabiaceae', 'Proteales', 'en'),
('Proteaceae', 'Proteales', 'en');

INSERT INTO plant_families
(family, traits, description, inflorescence_and_flowers, fruits_and_seeds, phytochemistry, photosynthesis, distribution, economics)
VALUES
-- First, some ornamentals:
('Iridaceae', NULL, 'contains irises but also other bulbs, corms and rhizomes including crocus and gladiolus', 'flower parts in multiples of three: three sepals, three true petals and three stamens', NULL, NULL, NULL, NULL, NULL),
('Scrophulariaceae', NULL, 'figwort, foxglove, penstemon and buddleja', 'Many have two-lipped, tubular flowers, often born on long spires', NULL, NULL, NULL, NULL, NULL),
('Saxifragaceae', NULL, 'typically perennial and herbaceous. The most well-known garden genera include Saxifraga, Heuchera, Astilbe, Rodgersia and Tiarella.', NULL, NULL, NULL, NULL, NULL, NULL),
('Crassulaceae', NULL, 'The stonecrop family comprises fleshy, succulent, plants, which store water in the leaves and are extremely drought-tolerant. They include Aeonium, Crassula, Echeveria, and Sempervivum.',  NULL, NULL, NULL,  NULL, NULL, NULL),
('Liliaceae', NULL, 'Many popular garden plants are members of the lily family, including Erythronium, fritillary, lily and tulip.',  'typically have elaborate blooms, as plants in this family have evolved a close relationship with pollinators', NULL, NULL,  NULL, NULL, NULL),
('Ranunculaceae', NULL, 'The buttercup, family includes many popular garden plants, including clematis, delphinium and aquilegia. The family takes its name from the latin, rana, which means ‘little frog’, because a lot of the plants thrive in damp places.',  NULL, NULL, NULL,  NULL, NULL, NULL),

('Asteraceae', 'aster, sunflower family', 'Most are evergreen shrubs or subshrubs or perennial rhizomatous herbs, but tap-rooted or tuberous-rooted perennials, and biennial and annual herbs are also frequent.\nCommon genera of this family include: Achillea (yarrow), Dahlia (dahlia), Jacobaea (dusty miller), Leucanthemum (daisy), Symphyotrichum (aster), and Taraxacum (dandelion).\nThe leaves are alternate or opposite, rarely whorled, and often lobed or toothed and pinnately or palmately veined',  'an inflorescence that is a composite head with disc florets, (ray florets may or may not be present)', 'an achene-like cypsela (fruit) with a fringe of hairs or papus', NULL,  NULL, NULL, NULL),
-- ('FAMILY', NULL, 'DESCRIPTION',  NULL, NULL, NULL,  NULL, 'DISTRIBUTION'/NULL, 'ECONOMICS'/NULL),
-- ('FAMILY', NULL, 'DESCRIPTION',  NULL, NULL, NULL,  NULL, 'DISTRIBUTION'/NULL, 'ECONOMICS'/NULL),
-- ('FAMILY', NULL, 'DESCRIPTION',  NULL, NULL, NULL,  NULL, 'DISTRIBUTION'/NULL, 'ECONOMICS'/NULL),
-- ('FAMILY', NULL, 'DESCRIPTION',  NULL, NULL, NULL,  NULL, 'DISTRIBUTION'/NULL, 'ECONOMICS'/NULL),
('Chenopodiaceae', NULL, 'The Chenopodioideae are annual or perennial herbs, subshrubs, shrub or small trees. The leaves are usually alternate and flat.\nA subfamily of the flowering plant family Amaranthaceae in the APG III system, which is largely based on molecular phylogeny, but were included – together with other subfamilies – in the family Chenopodiaceae, or goosefoot family, in the Cronquist system.',  'The flowers are often unisexual. Many species are monoecious or have mixed inflorescences of bisexual and unisexual flowers. Some species are dioecious, like Spinacia, Grayia, Exomis, and Atriplex. In several species of tribe Atripliceae, the female flowers are without perianth, but enclosed by two bracts. The species with a perianth have up to five tepals. The seed is horizontal or vertical, with annular or horseshoe-shaped embryo.', NULL, NULL,  NULL, 'Distributed worldwide, but originates from Eurasia.', NULL),

('Amaranthaceae',
 'The basic chromosome number is (rarely 6) mostly 8–9 (rarely 17).',
 'Amaranthaceae is a family of flowering plants commonly known as the amaranth family, in reference to its type genus Amaranthus. It includes the former goosefoot family Chenopodiaceae and contains about 165 genera and 2,040 species, making it the most species-rich lineage within its parent order, Caryophyllales. Most species in the Amaranthaceae are annual or perennial herbs or subshrubs; others are shrubs; very few species are vines or trees. Some species are succulent. Many species have stems with thickened nodes. The wood of the perennial stem has a typical anomalous secondary growth; only in subfamily Polycnemoideae is secondary growth normal. The leaves are simple and mostly alternate, sometimes opposite. They never possess stipules. They are flat or terete, and their shape is extremely variable, with entire or toothed margins. In some species, the leaves are reduced to minute scales. In most cases, neither basal nor terminal aggregations of leaves occur.',
 'The flowers are solitary or aggregated in cymes, spikes, or panicles and typically perfect (bisexual) and actinomorphic. Some species have unisexual flowers. Bracts and bracteoles are either herbaceous or scarious. Flowers are regular with an herbaceous or scarious perianth of (one to) mostly five (rarely to eight) tepals, often joined. One to five stamens are opposite to tepals or alternating, inserting from a hypogynous disc, which may have appendages (pseudostaminodes) in some species. The anthers have two or four pollen sacs (locules). In tribe Caroxyloneae, anthers have vesicular appendages. The pollen grains are spherical with many pores (pantoporate), with pore numbers from a few to 250 (in Froelichia). One to three (rarely six) carpels are fused to a superior ovary with one (rarely two) basal ovule. Idioblasts are found in the tissues.',
 'The diaspores are seeds or fruits (utricles), more often the perianth persists and is modified in fruit for means of dispersal. Sometimes even bracts and bracteoles may belong to the diaspore. More rarely the fruit is a circumscissile capsule or a berry. The horizontal or vertical seed often has a thickened or woody seed coat. The green or white embryo is either spirally (and without perisperm) or annular (rarely straight).',
 'Widespread in the Amaranthaceae is the occurrence of betalain pigments. The former Chenopodiaceae often contain isoflavonoids.In phytochemical research, several methylenedioxyflavonols, saponins, triterpenoids, ecdysteroids, and specific root-located carbohydrates have been found in these plants.',
 'Although most of the family use the more common C3 photosynthesis pathway, around 800 species are C4 plants; this makes the Amaranthaceae the largest group with this photosynthesis pathway among the eudicots (which collectively includes about 1,600 C4 species). Within the family, several types of C4 photosynthesis occur, and about 17 different types of leaf anatomy are realized. Therefore, this photosynthesis pathway seems to have developed about 15 times independently during the evolution of the family. About two-thirds of the C4 species belong to the former Chenopodiaceae. The first occurrence of C4 photosynthesis dates from the early Miocene, about 24 million years ago, but in some groups, this pathway evolved much later, about 6 (or less) million years ago.The multiple origin of C4 photosynthesis in the Amaranthaceae is regarded as an evolutionary response to inexorably decreasing atmospheric CO2 levels, coupled with a more recent permanent shortage in water supply as well as high temperatures. Species with higher water-use efficiency had a selective advantage and were able to spread out into arid habitats.>',
 'Amaranthaceae is a widespread and cosmopolitan family from the tropics to cool temperate regions. The Amaranthaceae (sensu stricto) are predominantly tropical, whereas the former Chenopodiaceae have their centers of diversity in dry temperate and warm temperate areas. Many of the species are halophytes, tolerating salty soils, or grow in dry steppes or semi-deserts.',
 'Some species, such as spinach (Spinacia oleracea) or forms of beet (Beta vulgaris) (beetroot, chard), are used as vegetables. Forms of Beta vulgaris include fodder beet (Mangelwurzel) and sugar beet. The seeds of Amaranthus, lamb''s quarters (Chenopodium berlandieri), quinoa (Chenopodium quinoa) and kañiwa (Chenopodium pallidicaule) are edible and are used as pseudocereals. Dysphania ambrosioides (epazote) and Dysphania anthelmintica are used as medicinal herbs. Several amaranth species are also used indirectly as a source of soda ash, such as members of the genus Salicornia (see glasswort). A number of species are popular garden ornamental plants, especially species from the genera Alternanthera, Amaranthus, Celosia, and Iresine. Other species are considered weeds, e.g., redroot pigweed (Amaranthus retroflexus) and alligatorweed (Alternanthera philoxeroides), and several are problematic invasive species, particularly in North America, including Kali tragus and Bassia scoparia. Many species are known to cause pollen allergies.'),
('Anacardiaceae',
 NULL,
 'Anacardiaceae are resinous trees or shrubs. Leaves are alternate and often trifoliolate or pinnately compound, though some species bear simple leaves. The small, often unisexual, 5-merous flowers have a prominent intrastaminal nectary disk. Fruits are usually 1-seeded drupes. Anacardiaceae comprise more than 700 species in 78 genera.\nRhus, the largest genus has 200 species. The family is pantropical but contains some temperate members.\nEdible members of the family include cashew (Anacardium occidentale), mango (Mangifera indica), and pistachio (Pistacia vera), and hogplums and their relatives (Spondias cytherea, S. mombin, S. purpurea, and S. radlkoferi). Fruits of Schinus molle and Schinus terebinthifolius are used to adulterate black pepper (Piper nigrum). The latter species is an invasive shrub in many parts of the tropics and subtropics. Toxicodendron vernicifluum (lacquer tree) is the source of urushi lacquer. Sap from the unripe fruit of Semecarpus anacardium is used as a dye. Schinopsis quebracho-colorado and several species of Schinopsis Rhus are harvested for tannins. Anacardium, Campnosperma, Dracontomelon, Gluta, Koordersiodendron, Metopium, and Tapirira species provide timber. Species of Metopium, Rhus, Semecarpus, and Toxicodendron are toxic.',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL),
('Apiaceae (Umbelliferae)',
 NULL,
 'Apiaceae are usually aromatic herbs or shrubs with sheathing leaf bases. The simple or compound leaves are alternate. Blades often are deeply dissected. The very small 5- merous flowers have an inferior ovary composed of 2-5 connate carpels. Umbelliferae refers to the characteristic umbellate inflorescence. Fruits are usually dry schizocarps. The cosmopolitan Apiaceae contains 3,780 species in 434 genera. Genera containing more than 100 species include Eryngium (250), Ferula (190), Pimpinella (150), Angelica (110), and Bupleurum (100)',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'The family, which includes many herbs and spices, medicines, would rank among the ten most important families. Apiaceae are best know known as a source of important culinary herbs and spices including anise (Pimpinella anisum), cilantro and coriander (Coriandrum sativum), cumin (Cuminum cyminum), dill (Anethum graveolens), parsley (Petroselinium crispum), caraway (Carum carvi), and cilantro (Eryngium foetidum). Carrots, the tuberous root of Daucus carrota, are one of the world''s top vegetables. Other edible members of the family include celerey (Apium graveolens), fennel root (Foeniculum vulgare), parsnip (Pastinaca sativa) and the Andean crop arracacha (Arracacia xanthorhizza). Most of the edible members of the family also have medicinal value. The family is noted for the presence of bioactive polyactetylenic compounds. Other well-known medicinal plants in the family are dong quai (Angelica sinensis) and gotu kola (Centella asiatica). Poison hemlock Conium maculatum, implicated in the death of Socrates, contains the neurotoxin coniine'),
('Araliaceae', NULL, '43 genera and around 1500 species consisting of primarily woody plants and some herbaceous plants commonly called the ginseng family.\n', 'simple umbels', NULL, NULL, NULL, 'woody, Tropics', 'ornamentals foliage genera like Hedera (ivies), Fatsia (Japanese aralias) and Heptapleurum; ginseng'),
('Arecaceae (Palmae)',
 NULL,
 'Arecaceae are slender trees or shrubs usually with an unbranched trunk. Notable exceptions to the unbranched trunk are Serenoa and some Euterpe species. The family also includes several genera of climbers. The large, palmately or pinnately lobed, compound leaves are densely clustered at the apex of the stem. They have a well-developed basal sheath. The small trimerous flowers are often unisexual. The gynoecium is usually syncarpous, with 3 carpels united to form a superior ovary. Fruits commonly are fleshy, though sometimes dry, drupes. Palm inflorescences typically are large, branched, and subtended by a spathe. Areaceae includes 2,500 species in 191 genera. The pantropical family is most divers in equatorial regions but also occurs in warm-temperate regions.',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'Palms have been called the trees of life. Date palms and coconut palms probably have more individual uses than any other species in the world. In addition to those two species, African oil palm (Elaeis guineensis) ranks among the most widely cultivated species. Date palms (Phoenix dactylifera) are among the oldest cultivated tree crops. Today production estimates are as high as 4,000,000 tons of fruits per year. African oil palms can produce 250 kg of quality palm kernel oil and 500 kg of kernel meal per hectare. Coconuts (Cocos nucifera) are symbolic of the multiple uses for which palms can be employed. The hard endosperm of the seed is edible fresh. It can also be dried to produce copra. The liquid endosperm or coconut water is potable. Coconut milk is made by grating coconut with hot water. The fruits also supply food for domesticated animals, especially pigs. Where coconuts are grown in large quantities, non-edible parts of the fruit are used for fuel and are a good source of charcoal. The hard endocarp is used for bowls. Sap from the inflorescence is tapped to produce sugar or it may be fermented to produce an alcoholic beverage. Coir is derived from the mesocarp fibers that surround the seed and is used to manufacture mats, brushes, twine and rope. Coconut leaves are split longitudinally for roof thatch. Baskets, back pats, and hats are woven from the leaf. The plant also is employed in medicines and cosmetics.\nIn addition to the tree species mentioned above, many other palms are important food sources. Peach palm (Bactris gasipaes) is a major staple for many cultures in Central and Northern South America. In Amazonian Ecuador, the Shuar refer to the palm as uwe, and celebrate its annual harvest with a festival. The doum palm (Hyphaene thebaica) was considered to be a sacred tree in ancient Egypt. Where the sago palm (Metroxylon sagu) grows in Indonesia, it is said “nobody ever goes hungry.” Starch is obtained by soaking pieces of the stem in water. Sugar palm (Arenga pinnata) is the source of jaggery or palm sugar. The apical mersitems of several Euterpe species are among the preferred sources of palm hearts.\nPalms also are important fiber sources. For example, Wounaan and Emberá weave baskets from the leaves of Astrocaryum standleyanum. The Seminoles of southern Florida are famous for their dolls, made from the petiole fibers of Serenoa repens. Raphia spp. from Africa are commercially important sources of fiber used for crafts. One of the most valuable non-food palm product is rattan, used as a structural material for furniture known by the same name. Rattans are Old World climbers in the genus Calamus and related genera. Species from the New World genus Desmoncus are used similarly. Palms provide a plethora of other products. Carnauba wax is extracted from the leaves of Copernicia cerifera. Phytelephas aequatorialis and other species in the genus are the source of tagua or vegetable ivory. Betel nut palm (Areca catechu) is chewed to produce a stimulating effect due to arecoline and other muscarinic agonistic alkaloids. Palms also have medicinal value. Most notably, saw palmetto (Serenoa repens) is effective in treatment of benign prostatic hyperplasia. Finally palms are highly valued ornamentals, serve as the quintessential symbol of the tropics.'),
('Asparagaceae', NULL,
'(/əsˌpærəˈɡeɪsiˌaɪ, -siːˌiː/). In the order Asparagales of the monocots. The family name is based on the edible garden asparagus, Asparagus officinalis. This family includes both common garden plants as well as common houseplants. The garden plants include asparagus, yucca, bluebell, and hosta, and the houseplants include snake plant, corn cane, spider plant, and plumosus fern.',
NULL, NULL, NULL, NULL, NULL, NULL),
('Brassicaceae', -- formerly Cruciferae
 NULL,
 'Brassicaceae are shrubs or herbaceous plants with acrid juice. The latter is due to glucosinolates, which are responsible for the distinctive taste of many members of the family. The alternate leaves are simple, or pinnately lobed, and often forming basal rosettes. Flowers have four clawed petals that are cross-shaped, hence the original family name Cruciferae. Stamens often are distinctly tetradynamous, with 2 short and four long filaments. The carpel, which is borne on a gynophore, mature into capsular fruits called siliques or silicles. Brassicaceae include more than 3,700 species in 338 genera. The family is cosmopolitan but most diverse in the Mediterranean. Genera containing more than 100 species include Draba (365), Cardamine (200), Erysimum (225), Lepidium (230), Alyssum (195), Arabis (120), and Physaria).',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'The many varieties of Brassica oleracea include broccoli, cauliflower, cabbage, collard greens, Brussel sprouts, kale, and kohlrabi. Turnip (Brassica rapa) has an edible taproot and edible leaves. Rutabaga (Brassica napus) and daikon and radish (Raphanus sativus) are other members of the family with edible taproots. Maca (Lepidium meyenii) is an important crop in the Andes. Brassicaceae is the source of several well known condiments including mustard (Brassica nigra and Sinapis alba), horseradish (Armoracia rusticana), and wasabi (Eutrema wasabi). Watercress (Nasturtium officinale) leaves are edible. Rapeseed (Brassica napus) is the world''s third most important oil seed crop.'),
('Convolvulaceae',
 NULL,
 'Convolvulaceae are mostly vines, though the family includes some herbs and a few arborescent taxa. Cuscuta and its relatives are parasitic vines. Sometimes treated separately, molecular data supports their inclusion in Convolvulaceae. Milky latex is characteristic though not always obvious. The alternate, simple, are often cordate. Margins are generally entire, but some species have divided margins. The five-merous corolla is usually large showy, funnelform, plicate and convolute. The gynoecium is composed of 2 connate carpels, with a superior ovary. Fruits are capsules with 2 ovules per locule. The family, which includes about 1600 species in 57 genera, is most common in the tropics, though temperate members are common. Genera bearing more than 100 species include Ipomoea (600), Convolvulus (250), Cuscuta (150), and Jacquemontia (120).',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'The most important species in the family is sweet potato (Ipomoea batatas), which ranks among the 10 most important world crops. Turbina corymbosa (olouqui) and Ipomoea tricolor (badoh negro) are rich in alkaloids, along with many other members of the family. Ololiqui contains the alkaloid d-Lysergic acid amide to d-lysergic acid diethylamide, commonly known as LSD. Several species in the family are employed as purgatives. Ipomoea and Convolvulus species are significant weeds in agricultural fields. The two preceding genera along with Evolvulus and Jacquemontia are sometimes cultivated as ornamentals.'),
('Cucurbitaceae',
 NULL,
 'Cucurbitaceae are coarse vines with spirally coiled tendrils at the base of the petiole. The alternate pinnately lobed or compound leaf blades are often scabrous. Corollas are five lobed, actinomorphic and often large. Flowers are unisexual. Staminate flowers appear to have 5 stamens but appear to have 3 as two pairs are fused. The gynoecium consists of 3 connate carpels with an inferior ovary. Fruits are modified berries, known as pepos or capsules. Cucurbitaceae are cosmopolitan but most species occur in the tropics or subtropical regions. The family includes 845 species in 118 genera. Major genera include Cayaponia (60), Momordica (45), Gurania (40), Sicyos (40), Coccinia (30), and Cucurbita (27).',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'Squashes (Cucurbita spp.) along with beans and corn were the “three sisters” of Meso-American cultures. Cucurbita argyrosperma, C. maxima, C. moschata, and C. pepo are the sources of pumpkins, squashes, and zucchini. Cucumis melo is the source of cantaloupes and honeydew melons. Cucumber (Cucumis sativus ) and watermelon (Citrullus lanatus) are other important member of the family. All are grown throughout the tropics and subtropics. Chayote (Sechium edule) and achocha (Cyclanthera pedata) are cultivated in the New World tropics for their edible fruits. The bitter melon (Momordica charantia) is common in Asian markets. Mature Luffa cylindrica fruits are the source of a vegetable sponge. Dried Lagenaria siceraria fruits are called bottle gourds. Fevillea cordifolia seeds are a potential oil crop. Several species of Cucurbitaceae have medicinal value. Momordica charantia has been shown to be effective in treating diabetes.'),
('Dioscoreaceae',
 NULL,
 'Dioscoreaceae are twining vines or lianas with thick rhizomes. The alternate leaves usually alternate and cordate. Flowers are small and mostly unisexual with six tepals, 6, stamens 6, connate carpels with an inferior ovary. Plants are dioecious. Fruits are mostly 3-winged loculicidal capsules. Dioscoreaceae are mostly tropical with a few temperate and subtropical members. The family has 870 species in three genera, though most species are found in Dioscorea.',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'The tubers of several species (Dioscorea alata, D. bulbifera, D. cayenensis, D. dumetorum, D. esculenta, D. glabra, D. hispida, D. opposita, D. pentaphylla, D. rotundata, and D. trifida) are cultivated for their edible tubers. They are the most important staple for many tropical cultures. Of equal importance, Mexican species of Dioscorea (including D. mexicana) were the source of diosgenin, which was employed to synthesize progesterone for the first synthetic birth control pills.'),
('Euphorbiaceae',
 NULL,
 'The spurge family is a huge family that contains spurges such as Euphorbia, but also cassava and some woody shrubs and trees. Many plants in this family have toxic leaves, fruit or sap.\nEuphorbiaceae are herbs, vines, shrubs or trees often with milky latex. Leaves are mostly alternate and simple, though some taxa have compound leaves and a few have opposite leaf arrangements. Inflorescences are cymose and sometimes arranged in cyathia. Flowers are unisexual (plants monoecious or dioecious). The perianth is mostly inconspicuous or absent. Stamens are 5 to many or sometimes reduced to one. The gynoecium usually consists of 3 connate carpels with 1 ovule per locule (taxa with two ovules per locule that formerly were included in Euphorbiaceae are now place in Phyllanthaceae and Picrodendraceae). Fruits are usually schizocarps. Euphorbiaceae contains 5,970 species in 222 genera. Major genera are Euphorbia (2,000), Croton (750), Acalypha (400), Macaranga (250), Manihot (150), Tragia (150), and Jatropha (150). The family is cosmopolitan but best developed in the tropics and subtropics.',
 'When viewed as a whole, the head of flowers looks like a single flower (a pseudanthium). It has a unique kind of pseudanthium, called a cyathium, where each flower in the head is reduced to its barest essential part needed for sexual reproduction. The individual flowers are either male or female, with the male flowers reduced to only the stamen, and the females to the pistil. These flowers have no sepals, petals, or other parts that are typical of flowers in other kinds of plants. Structures supporting the flower head and other structures underneath have evolved to attract pollinators with nectar, and with shapes and colors that function in a way petals and other flower parts do in other flowers.',
 NULL,
 NULL,
 NULL,
 NULL,
 'Manioc or cassava (Manihot esculenta) roots are the major staple for many people in the tropics. Leaves of Cnidoscolus aconitifolius and C. chayamansa are sources of leafy vegetables. Caryodendron orinocense, an Amazonian species, produces an edible seed and has the potential for commercial development. Euphorbiaceae species are significant sources of oils (candlenut - Aleurites fordii, tung oil - A. moluccanus, castor oil - Ricinus communis) and waxes (Euphorbia antisyphilitica and Sapium sebiferum). Ranking with manioc in terms of human value is para rubber (Hevea brasiliensis). The family also is an important source of medicines including castor oil, sangre de grado (Croton spp.). Recently ethnobotanical leads from Paul Cox''s work in Samoa led to the development of the AID''s drug prostratin from Homalanthus nutans. Hura crepitans and Hippomane mancinella are notoriously toxic. The family also provides many ornamentals, most notably Euphorbia pulcherrima.'),
('Fabaceae (Leguminosae)',
 NULL,
 'Fabaceae are herbs, shrubs, trees, lianas or vines usually bearing alternate, pinnately compound, pulvinate, stipulate leaves. N-fixing bacteria are common in two subfamilies: Mimosoideae and Papilionoideae. The androperianth is 5-merous with 10 to numerous stamens (Mimosoideae). The gynoecium consists of a single carpel with 2 to many ovules. Fruits are usually legumes, splitting along two sutures but sometimes indehiscent. The cosmopolitan family contains an estimated 18,000 species in 630 genera. Twenty genera account for nearly half of the species in the family and 16 contain more than 200 species each: Astragalus (2,000), Acacia (1,000), Indigofera (700), Crotalaria (600), Mimosa (500), Desmodium (400), Tephrosia (400), Trifolium (300), Chamaecrista (260), Bauhinia (250), Senna (250), Inga (250), Dalbergia (200), Lupinus (200), Phaseolus (200), and Pithecellobium (200).',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'Fabaceae rank second to Poaceae with respect to human importance. Members of the subfamily Papilionoideae are significant non-animal protein sources. They include beans (Phaseolus spp., especially P. acutifolius, P. coccineus, P. lunatus, and P. vulgaris), broad bean (Vicia faba), cowpea (Vigna unguiculata), lentils (Lens culinaris, syn. L. esculenta), peas (Pisum sativum), peanut (Arachis hypogaea), soybean (Glycine max). Inga spp. (Mimosoideae) and Tamarindus indica (tamarind – Caesalpinioideae) are tree legumes cultivated for their edible fruits. Resins from balsam of Peru (Myroxylon balsamum), copaiba (Copaifera spp.) and coubaril (Hymenaea courbaril) are globally important commodities. Gum Arabic (Acacia Senegal) has a diverse array of culinary and industrial uses. Clovers (Trifolium and Medicago spp.) are commonly cultivated as forage plants or to improve soil fertility. Indigo (Indigofera tinctoria) and logwood (Haematoxylum campechianum) are major sources of dyes. Fabaceae are rich in alkaloids. In addition to their medicinal value (e.g., physostigmine from Physostigma venenosum) some species are hallucinogenic (yopo - Anadenanthera peregrina). Lonchocarpus (esp. L. nicou ) and related species are the source of rotenone, which is used as a fish poison and insecticide. The legume family also is rich in timber species. Black Locust (Robinia pseudoacacia) is one of the most commonly cultivated timber trees in the temperate zone. Rosewood (Dalbergia spp.) from Brazil, India, and Honduras is prized for the construction of musical instruments, especially guitars. The most highly valued species is Brazilian rosewood (Dalbergia nigra). Many legumes are planted as ornamentals. Royal Poinciana (Delonix regia), native of Madagascar, is ubiquitous in the tropics.'),
('Lamiaceae',
 NULL,
 '(Labiatae). [The mint family] contains familiar garden herbs such as lavender, basil, mint, oregano, thyme and rosemary. Most plants in this family have aromatic foliage and many are grown for their culinary and medicinal properties because of the oils produced when the leaves and flowers are crushed or distilled.\nLamiaceae, as now circumscribed, includes aromatic herbs, shrubs or trees, with opposite, leaves and square stems. Many were formerly placed in Verbenaceae. Another legitimate name for Lamiaceae sensu strictu is Labiatae. Inflorescences are determinate, often of paired cymes. Flowers are zygomorphic to occasionally actinomorphic, perfect, often with a nectariferous disk. The 5-merous calyx is synsepalous; the 5-merous corolla is sympetalous and typically bilabiate. The epipetalous stamens are 4 (didynamous or equal) sometimes reduced to 2. The gynoecium consists of 2 fused carpels united to form a 2-locular (but appearing 4 locular), superior ovary. The style is gynobasic. Fruits are schizocarps that split into 4 nutlets or are drupes. The cosmopolitan family comprises 7,136 species in 236 genera. Genera with 250 or more species include Salvia (800), Hyptis (400), Clerodendrum (400), Thymus (350), Plectranthus (300), Scutellaria (300), Stachys (300), Nepeta (250), and Vitex (250).',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'The family is best known as a source of culinary herbs including basil Ocimum basilicum, marjoram (Origanum majorana), mint (Mentha spp.), oregano (Origanum vulgare), rosemary (Rosmarinus officinalis), sage (Salvia officinalis), savory (Satureja hortensis), and thyme (Thymus vulgaris). Cuban oregano (Plectranthus amboinicus) is cultivated widely in the tropics, both as a culinary herb and a medicine. The roots or tubers of Chinese artichoke (Stachys sieboldii var. sieboldii, syn. Stachys affinis), gala dinich (Coleus edulis), Huasa potato (Plectranthus rotundifolius), and Kaffir potato (Plectranthus esculentus) are edible. Teak (Tectona grandis, formerly Verbenaceae) is one of the world''s most important timbers, valued for its use in marine applications. Gmelina arborea and species of Vitex (both genera formerly in Verbenaceae) also are timber sources. Several mint species are common in cosmetics and perfumes (e.g., lavender - Lavandula angustifolia and patchouli - Pogostemon cablin). All of the edible mints are valued for their medicinal uses. Many other species are employed for therapeutic purposes including Holy basil (Ocimum sanctum), hyssop (Hyssopus officinalis), lemon balm (Melissa officinalis), motherwort (Leonurus cardiaca), peppermint (Mentha x piperita), and wild thyme (Thymus serpyllum). Salvia divinorum, native to Mexico, is a potent hallucinogen. Lamiaceae also provide many ornamentals.'),
('Lauraceae',
 NULL,
 'Lauraceae, or the laurels, is a plant family that includes the true laurel and its closest relatives. This family comprises about 2850 known species in about 45 genera worldwide. They are dicotyledons, and occur mainly in warm temperate and tropical regions, especially Southeast Asia and South America. Many are aromatic evergreen trees or shrubs, but some, such as Sassafras, are deciduous, or include both deciduous and evergreen trees and shrubs, especially in tropical and temperate climates. The genus Cassytha is unique in the Lauraceae in that its members are parasitic vines. Most laurels are highly poisonous.',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL),
('Malvaceae (Mallows)',
 NULL,
 'Malvaceae (/mælˈveɪsiˌaɪ, -siːˌiː/), or the mallows, is a family of flowering plants estimated to contain 244 genera with 4225 known species. Well-known members of economic importance include okra, cotton, cacao, roselle and durian. There are also some genera containing familiar ornamentals, such as Alcea (hollyhock), Malva (mallow), and Tilia (lime or linden tree). The genera with the largest numbers of species include Hibiscus (434 species), Pavonia (291 species), Sida (275 species), Ayenia (216 species), Dombeya (197 species), and Sterculia (181 species).',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'A number of species are pests in agriculture, including Abutilon theophrasti and Modiola caroliniana, and others that are garden escapees. Cotton (four species of Gossypium), kenaf (Hibiscus cannabinus), cacao (Theobroma cacao), kola nut (Cola spp.), and okra (Abelmoschus esculentus) are important agricultural crops. The fruit and leaves of baobabs are edible, as is the fruit of the durian. A number of species, including Hibiscus syriacus, Hibiscus rosa-sinensis and Alcea rosea are garden plants.'),
('Meliaceae',
 NULL,
 'Meliaceae, the mahogany family, is a flowering plant family of mostly trees and shrubs (and a few herbaceous plants, mangroves) in the order Sapindales.\nThey are characterised by alternate, usually pinnate leaves without stipules, and by syncarpous, apparently bisexual (but actually mostly cryptically unisexual) flowers borne in panicles, cymes, spikes or clusters. Most species are evergreen, but some are deciduous, either in the dry season or in winter.\nThe fossil record of the family extends back into the Late Cretaceous.',
 NULL,
 NULL,
 NULL,
 NULL,
 'The family includes about 53 genera and about 600 known species, with a pantropical distribution; one genus (Toona) extends north into temperate China and south into southeast Australia, another (Synoum) into southeast Australia, and another (Melia) nearly as far north. They most commonly grow as understory trees in rainforests, but are also found in mangroves and arid regions.',
 NULL),
('Moraceae',
 NULL,
 'The Moraceae—often called the mulberry family or fig family—are a family of flowering plants comprising about 38 genera and over 1100 species. Most are widespread in tropical and subtropical regions, less so in temperate climates; however, their distribution is cosmopolitan overall. The only synapomorphy within the Moraceae is presence of laticifers and milky sap in all parenchymatous tissues, but generally useful field characters include two carpels sometimes with one reduced, compound inconspicuous flowers, and compound fruits. The family includes well-known plants such as the fig, banyan, breadfruit, jackfruit, mulberry, and Osage orange. The "flowers" of Moraceae are often pseudanthia (reduced inflorescences).',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL),
('Musaceae',
 NULL,
 'Musaceae is a family of flowering plants composed of three genera with about 91 known species, placed in the order Zingiberales. The family is native to the tropics of Africa and Asia. The plants have a large herbaceous growth habit with leaves with overlapping basal sheaths that form a pseudostem making some members appear to be woody trees. In most treatments, the family has three genera, Musa, Musella and Ensete. Cultivated bananas are commercially important members of the family, and many others are grown as ornamental plants.',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL),
('Myrtaceae',
 NULL,
 'Myrtaceae (/mərˈteɪsiˌaɪ, -siːˌiː/), the myrtle family, is a family of dicotyledonous plants placed within the order Myrtales. Myrtle, pōhutukawa, bay rum tree, clove, guava, acca (feijoa), allspice, and eucalyptus are some notable members of this group. All species are woody and contain essential oils. The leaves are evergreen, alternate to mostly opposite, simple, and usually entire (i.e., without a toothed margin).',
 'All species have flower parts in multiples of four or five. They have a base number of five petals, though in several genera, the petals are minute or absent. The stamens are usually very conspicuous, brightly coloured, and numerous.',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL),
('Oleaceae',
 NULL,
 'Oleaceae, also known as the olive family or sometimes the lilac family, is a taxonomic family of flowering shrubs, trees, and a few lianas in the order Lamiales. It presently comprises 28 genera, one of which is recently extinct. The extant genera include Cartrema, which was resurrected in 2012. The number of species in the Oleaceae is variously estimated in a wide range around 700. The flowers are often numerous and highly odoriferous. Notable members include olive, ash, jasmine, and several popular ornamental plants including privet, forsythia, fringetrees, and lilac.',
 NULL,
 NULL,
 NULL,
 NULL,
 'subcosmopolitan distribution, ranging from the subarctic to the southernmost parts of Africa, Australia, and South America',
 NULL),
('Pinaceae',
 NULL,
 'The Pinaceae (/pɪˈneɪsiːˌiː, -siˌaɪ/), or pine family, are conifer trees or shrubs, including many of the well-known conifers of commercial importance such as cedars, firs, hemlocks, piñons, larches, pines and spruces. The family is included in the order Pinales, formerly known as Coniferales. Pinaceae have distinctive cones with woody scales bearing typically two ovules, and are supported as monophyletic by both morphological trait and genetic analysis. They are the largest extant conifer family in species diversity, with between 220 and 250 species (depending on taxonomic opinion) in 11 genera, and the second-largest (after Cupressaceae) in geographical range, found in most of the Northern Hemisphere, with the majority of the species in temperate climates, but ranging from subarctic to tropical. The family often forms the dominant component of boreal, coastal, and montane forests. One species, Pinus merkusii, grows just south of the equator in Southeast Asia. Major centres of diversity are found in the mountains of southwest China, Mexico, central Japan, and California.',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL),
('Piperaceae',
 NULL,
 'The Piperaceae (/ˌpɪpəˈreɪʃiː/), also known as the pepper family, are a large family of flowering plants. The group contains roughly 3,600 currently accepted species in 5 genera. The vast majority of species can be found within the two main genera: Piper (2,171 species) and Peperomia (over 1,000 species).\nMembers of the Piperaceae may be small trees, shrubs, or herbs.\nThe best-known species, Piper nigrum, yields most peppercorns that are used as spices, including black pepper, although its relatives in the family include many other spices.',
 NULL,
 NULL,
 NULL,
 NULL,
 'The distribution of this group is best described as pantropical.',
 NULL)
, 
('Poaceae',
 NULL,
 'Poaceae (/poʊˈeɪsiaɪ, -siːiː/) or Gramineae (/ɡrəˈmɪniaɪ/) is a large and nearly ubiquitous family of monocotyledonous flowering plants commonly known as grasses. It includes the cereal grasses, bamboos, the grasses of natural grassland and species cultivated in lawns and pasture. The latter are commonly referred to collectively as grass.\nWith around 780 genera and around 12,000 species, the Poaceae is the fifth-largest plant family, following the Asteraceae, Orchidaceae, Fabaceae and Rubiaceae.',
 NULL,
 NULL,
 NULL,
 'There are both C3 and C4 grasses, referring to the photosynthetic pathway for carbon fixation. The C4 grasses have a photosynthetic pathway, linked to specialized Kranz leaf anatomy, which allows for increased water use efficiency, rendering them better adapted to hot, arid environments.',
 NULL,
 'The Poaceae are the most economically important plant family, providing staple foods from domesticated cereal crops such as maize, wheat, rice, barley, and millet as well as feed for meat-producing animals. They provide, through direct human consumption, just over one-half (51%) of all dietary energy; rice provides 20%, wheat supplies 20%, maize (corn) 5.5%, and other grains 6%. Some members of the Poaceae are used as building materials (bamboo, thatch, and straw); others can provide a source of biofuel, primarily via the conversion of maize to ethanol.'),
 -- (family, traits, description, inflorescence_and_flowers, fruits_and_seeds, phytochemistry, photosynthesis, distribution, economics)
 ('Proteaceae',
  NULL,
  'DESC',
  'FLOWER',
  'FRUIT-SEED',
  'PHYTOCHEM',
  'PHOTOSYNTHESIS',
  'predominantly in the Southern Hemisphere',
  'Many traditional cultures have used Proteaceae as sustenance, medicine, for curing animal hides, as a source of dyes, firewood and as wood for construction.\nTwo species of Macadamia are cultivated commercially for their edible nuts. Gevuina avellana (Chilean hazel) is also cultivated for its edible nuts, in Chile and New Zealand, and they are also used in the pharmaceutical industry for their humectant properties and as an ingredient in sunscreens. It is the most cold-resistant of the tree families that produce nuts.'),
('Rosaceae',
 NULL,
 'Rosaceae (/roʊˈzeɪsiː.iː, -si.aɪ/), the rose family, is a medium-sized family of flowering plants that includes 4,828 known species in 91 genera.\nThe name is derived from the type genus Rosa. Among the most species-rich genera are Alchemilla (270), Sorbus (260), Crataegus (260), Cotoneaster (260), Rubus (250), and Prunus (200), which contains the plums, cherries, peaches, apricots, and almonds. However, all of these numbers should be seen as estimates—much taxonomic work remains.\nThe family Rosaceae includes herbs, shrubs, and trees. Most species are deciduous, but some are evergreen.',
 'open, bowl-shaped flowers with five petals and a cluster of stamens at the centre',
 NULL,
 NULL,
 NULL,
 'They have a worldwide range but are most diverse in the Northern Hemisphere.',
 'Many economically important products come from the Rosaceae, including various edible fruits, such as apples, pears, quinces, apricots, plums, cherries, peaches, raspberries, blackberries, loquats, strawberries, rose hips, hawthorns, and almonds. The family also includes popular ornamental trees and shrubs, such as roses, meadowsweets, rowans, firethorns, and photinias.'),
('Rubiaceae',
 NULL,
 'Rubiaceae (/ruːbiˈeɪsiːˌiː, -siˌaɪ/) is a family of flowering plants, commonly known as the coffee, madder, or bedstraw family. It consists of terrestrial trees, shrubs, lianas, or herbs that are recognizable by simple, opposite leaves with interpetiolar stipules and sympetalous actinomorphic flowers. The family contains about 13,500 species in about 620 genera, which makes it the fourth-largest angiosperm family. Rubiaceae has a cosmopolitan distribution; however, the largest species diversity is concentrated in the tropics and subtropics. Economically important genera include Coffea, the source of coffee, Cinchona, the source of the antimalarial alkaloid quinine, ornamental cultivars (e.g., Gardenia, Ixora, Pentas), and historically some dye plants (e.g., Rubia).',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL),
('Rutaceae',
 NULL,
 'The Rutaceae (/ruːˈteɪsiˌaɪ, -siːˌiː/) is a family, commonly known as the rue or citrus family, of flowering plants, usually placed in the order Sapindales.\nThey range in form and size from herbs to shrubs and large trees.',
 'They generally have flowers that divide into four or five parts, usually with strong scents.',
 NULL,
 NULL,
 NULL,
 NULL,
 'The most economically important genus in the family is Citrus, which includes the orange (C. × sinensis), lemon (C. × limon), grapefruit (C. × paradisi), and lime (various, mostly C. aurantifolia, the key lime). Boronia is a large Australian genus, some members of which are plants with highly fragrant flowers and are used in commercial oil production. Other large genera include Zanthoxylum, several species of which are cultivated for Sichuan pepper, Melicope, and Agathosma. About 160 genera are in the family Rutaceae.'),
('Solanaceae',
 NULL,
 'The Solanaceae (/ˌsɒləˈneɪsi.iː, -ˌaɪ/), or the nightshades, are a family of flowering plants that ranges from annual and perennial herbs to vines, lianas, epiphytes, shrubs, and trees, and includes a number of agricultural crops, medicinal plants, spices, weeds, and ornamentals. Many members of the family contain potent alkaloids, and some are highly toxic, but many—including tomatoes, potatoes, eggplant, bell and chili peppers—are used as food. The family belongs to the order Solanales, in the asterid group and class Magnoliopsida (dicotyledons). The Solanaceae consists of about 98 genera and some 2,700 species, with a great diversity of habitats, morphology and ecology.',
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 'The Solanaceae family includes a number of commonly collected or cultivated species. The most economically important genus of the family is Solanum, which contains the potato (S. tuberosum, in fact, another common name of the family is the "potato family"), the tomato (S. lycopersicum), and the eggplant or aubergine (S. melongena). Another important genus, Capsicum, produces both chili peppers and bell peppers.'),
('Vitaceae',
 'Most Vitis species have 38 chromosomes (n=19), but 40 (n=20) in subgenus Muscadinia, while Ampelocissus, Parthenocissus, and Ampelopsis also have 40 chromosomes (n=20) and Cissus has 24 chromosomes (n=12).',
 'The Vitaceae are a family of flowering plants, with 14 genera and around 910 known species, including common plants such as grapevines (Vitis spp.) and Virginia creeper (Parthenocissus quinquefolia).\nThey are found in the buckthorn order (Rhamnales), comprising 12 genera of woody plants, most of them tendril-bearing vines.\nThe family name is derived from the genus Vitis.',
 NULL,
 NULL,
 NULL,
 NULL,
 'Asia, North America, and Europe (tropical and subtropical areas)',
 'The berries of Vitis species, commonly known as grapes, are an important fruit crop and, when fermented, produce wine.\nSome species of the genus, such as the North American Vitis rupestris, Vitis riparia, Vitis berlandieri, and their hybrids, are commonly used as rootstocks because they are highly resistant to phylloxera (Daktulosphaira vitifoliae) and mildews.\nAbout 5000 true V. vinifera cultivars are utilized nowadays by the wine, table (fresh fruit), and raisin (dried fruit) grape industries of the world.');

INSERT INTO in_family (plant_name, family) VALUES
-- First some ornamentals:
('crocus',    'Iridaceae'),
('gladiolus', 'Iridaceae'),
-- ('PLANTNAME', 'FAMILY'),
-- ('PLANTNAME', 'FAMILY'),
-- ('PLANTNAME', 'FAMILY'),
-- ('PLANTNAME', 'FAMILY'),
-- ('PLANTNAME', 'FAMILY'),
-- ('PLANTNAME', 'FAMILY'),
-- ('PLANTNAME', 'FAMILY'),
-- Then the farming varieties:
('spinach', 'Amaranthaceae'),
('beet',    'Amaranthaceae'),
('quinoa',  'Amaranthaceae'),
('macadamia', 'Proteaceae'),
-- ('PLANTNAME', 'FAMILY'),
-- ('PLANTNAME', 'FAMILY'),
-- ('PLANTNAME', 'FAMILY'),
-- ('PLANTNAME', 'FAMILY'),
-- ('spinach',   'Chenopodioideae'),
-- ('PLANTNAME', 'Chenopodioideae'),
-- ('PLANTNAME', 'Chenopodioideae'),
-- ('PLANTNAME', 'Chenopodioideae'),
('bamboo', 'Poaceae'),
('corn', 'Poaceae'),
('wheat', 'Poaceae'),
('barley', 'Poaceae'),
('millet', 'Poaceae'),
('rye', 'Poaceae'),
('oats', 'Poaceae'),
('rice', 'Poaceae'),
('cabbage', 'Brassicaceae'),
('cauliflower', 'Brassicaceae'),
('broccoli', 'Brassicaceae'),
('kale', 'Brassicaceae'),
('radish', 'Brassicaceae'),
('turnip', 'Brassicaceae'),
('lavender', 'Lamiaceae'),
('basil',    'Lamiaceae'),
('oregano',  'Lamiaceae'),
('mint',     'Lamiaceae'),
('thyme',    'Lamiaceae'),
('rosemary', 'Lamiaceae'),
('cassava', 'Euphorbiaceae'),
('apple tree', 'Rosaceae'),
('pear tree',  'Rosaceae'),
('blackberry', 'Rosaceae'),
('apricot',    'Rosaceae'),
('raspberry',  'Rosaceae'),
-- The rose family is home to many garden favourites and edible crops. It includes roses but also many fruit genera, such as apples, pears, blackberries, apricots and raspberries
('sunflower', 'Asteraceae'),
('yarrow',    'Asteraceae');

-- UNLOCK TABLES;
-- COMMIT;

-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- SET autocommit=@old_autocommit;
